version: '3.8'

services:
  web:
    build: .
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symfony
    depends_on:
      - db

  db:
    image: mariadb:10.4.28
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youtube_prototype
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
